A theme button and pin code to access the site.
EskandarAtrakchi/multi-format-encryption-decryption pull request #4
Opened 2024-10-29 14:24 UTC by EoinFitzsimons

Entering a 4-digit PIN is now required to use the site's functions; at the moment, it is set in the code. The site has also been updated with a dark purple and light purple theme; the user can switch between them through a button at the top.

2024-10-29 14:25 UTC, EoinFitzsimons commented
I also put node modules ina git ignore

2024-10-30 14:19 UTC, DavidOConnor1 approved these changes

2024-10-30 18:36 UTC, EskandarAtrakchi requested changes
# Un-approved:

Can't approve changes, code conflicts with 
Davey's branch2 pull request.

suggest to team up and David and create only on branch to fix the same thing.

2024-11-11 15:02 UTC, closed without merging

2024-11-11 18:30 UTC, EskandarAtrakchi reviewed
The styling is good for now, and for the social media items