Pin & theme
EskandarAtrakchi/multi-format-encryption-decryption pull request #8
Opened 2024-11-11 15:02 UTC by EoinFitzsimons

Changes in css, html for the pin and theme button, then the js for both.

2024-11-11 18:28 UTC, EskandarAtrakchi reviewed
Very good start!

2024-11-12 12:35 UTC, EskandarAtrakchi requested changes
# Things to be aware of:
1. in get ignore you only need to add the /node_modules not packages
2. when you are using .env then no need to encrypt the PIN and save it in localStorage 
3. deployment of backend is required for this action to be completed
4. NodeJs good choice to be used to get the PIN working with express and dotenv libraries

2024-11-13 11:55 UTC, DavidOConnor1 approved these changes
The pin.js file should not be ignored while still in a development branch(I know this was changed), however the code overall looks good

2025-11-20 14:20 UTC, closed without merging

2025-12-09 13:16 UTC, EskandarAtrakchi reviewed
Changes in css, html for the pin and theme button, then the js for both worked well.